#!/bin/bash

REGEX_VERSION='^v([0-9.]+)$'
[[ $SOURCE_BRANCH =~ $REGEX_VERSION ]]

docker build \
       --build-arg octodns_version=${BASH_REMATCH[1]} \
       -f $DOCKERFILE_PATH \
       -t $IMAGE_NAME \
       .